version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: ~/repo

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

      - run: npm run-script build
      
      - run:
          name: Authenticate with registry
          command: |
            echo "@mozart89-test:registry=https://npm.pkg.github.com/" > ~/repo/.npmrc
            echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish --verbose
